# -*- coding: utf-8 -*-
"""Copy of WoMakersCode-BootcampDataAnalytics-Livia_Pavini_Zeviani

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1085FVio8EVCIlUR77_Je4ZL1SVNDlPz-

1 ) Para determinar se um candidato está qualificado para uma vaga de emprego, são aplicados dois critérios:

a) O candidato deve ter uma presença igual ou superior a 60% em um treinamento obrigatório.

b) O candidato deve ter uma média de desempenho igual ou superior a 7 em uma série de testes.

Para auxiliar na avaliação dos candidatos, você deve criar uma função que recebe uma lista de dicionários contendo o nome do candidato, a média de desempenho e a quantidade de horas de ausência do treinamento. Com esses dados, a função deve calcular se o candidato está qualificado ou não. A presença do candidato é calculada considerando que o treinamento teve um total de 60 horas e utilizando a fórmula:

(Total horas - número de faltas)/Total horas * 100;
"""

def avalia_candidato():
  avaliação = list()
  candidato = dict()
  candidato['nome'] = str(input('Nome do candidato: '))
  candidato['média'] = int(input('Média do candidato: '))
  candidato['faltas'] = int(input('Faltas do candidato: '))
  presenca = int((60 - candidato['faltas'])/60 * 100)

  if candidato['média'] >= 7 and presenca >=60:
      print(f'Candidatx {candidato["nome"]} está qualificado(a)')
  else:
    print(f'Candidatx {candidato["nome"]} não está qualificado(a)')

avalia_candidato()

"""2) Crie uma função que recebe uma palavra (string), separa todos os caracteres em uma lista, retorna esta lista e quantidade de letras."""

def separa_palavra():
  palavra = input('Digite uma palavra: ')
  print("Essa palavra forma a lista: ", list(palavra), "e essa lista tem", len(palavra), "caracteres")

separa_palavra()

"""3) Crie um programa que leia quanto dinheiro uma pessoa tem na carteira, e calcule quanto poderia comprar de cada moeda estrangeira. Considere a tabela de conversão abaixo:

Valor convertido em real:
*   Dólar Americano: 4,91
*   Peso Argentino: 0,02
*   Dólar Australiano: 3,18
*   Dólar Canadense: 3,64
*   Franco Suiço: 0,42
*   Euro:  5,36
*   Libra esterlina: 6,21








"""

dinheiro_real = float(input('Quanto você tem na carteira? R$'))
dolar_americano = dinheiro_real/4.91
peso_argentino = dinheiro_real/0.02
dolar_australiano = dinheiro_real/3.18
dolar_canadense = dinheiro_real/3.64
franco_suico = dinheiro_real/0.42
euro = dinheiro_real/5.36
libra_esterlina = dinheiro_real/6.21


print("Com {:.2f} você pode comprar: {:.2f} dólares americanos, {:.2f} pesos, {:.2f} dólares australianos, {:.2f} dólares canadenses, {:.2f} francos,{:.2f} euros e {:.2f} libras".format(dinheiro_real, dolar_americano, peso_argentino, dolar_australiano, dolar_canadense, franco_suico, euro, libra_esterlina) )

"""
4) O chefe decidiu premiar os melhores funcionários de sua empresa com um brinde. Para isso ela vai entregar um brinde para todos os funcionários que tiverem uma performance superior a média da equipe.

Elabore uma função que recebe uma lista de nome em formato de dict (dicionário) com nome do funcionário e a média do funcionário (Valor de 0 a 10). Esta função deve calcular a média da equipe, identificar quais funcionários tem média igual ou superior a média da equipe e retornar uma lista com o nome dos funcionários que possuem média igual ou superior a média da equipe. A ordem dos nomes da lista de retorno deve ser em ordem decrescente."""

def desempenho_funcionarios():
  func = dict()
  lista = list()
  #supondo que a equipe tenha 3 funcionários
  for c in range(0,3):
    func['nome'] = str(input('Nome do funcionário: '))
    func['média'] = int(input('Média do funcionário - de 0 a 10: '))
    #media_equipe = media_1 + media_2 + media_3/3

    lista.append(func.copy())
  for func in lista:
    for média in func.values():
      print(média, end = " , média: ")

  print(lista)

desempenho_funcionarios()

"""5) Na variável países_ano, temos uma lista de listas, em que cada elemento é uma lista de dois elementos, em que o primeiro é o nome de um país e o segundo é o ano em que a nação foi fundada."""

lista_paises = [["Brasil", "1500"],["Mexico","1519"], ["Inglaterra", "927"], ["Espanha","1978"], ["Escocia", "843"]]

"""Você deseja criar uma nova lista de listas a partir do exemplo (lista_paises), em que cada elemento é uma lista de dois elementos, sendo o primeiro o nome do país (como é na lista original) e o segundo é o número de anos desde a fundação do país (considere que o ano atual é 2023)."""

lista_paises = [["Brasil", "1500"],["Mexico","1519"], ["Inglaterra", "927"], ["Espanha","1978"], ["Escocia", "843"]]
nova_lista = []
ano_atual = 2023
lista_paises[0][1]



"""6) Um jogador de um jogo de vídeo game deseja subir de nível em seu personagem ao atingir 50 inimigos derrotados. Enquanto esse número não é alcançado, uma mensagem indicando quantos inimigos ainda faltam é exibida na tela.

"""

inimigos_derrotados = 0
nivel = 0

while (inimigos_derrotados < 50):

    print(f"Faltam {50 - inimigos_derrotados} inimigos para você mudar de nível!")

    inimigos_derrotados += 1

print("\nVocê atingiu o próximo nível!")
nivel = 1